[package]
name = "proc_macro_consumer"
version = "0.1.0"
authors = ["Miguel Torres <migueltorreslopez@gmail.com>"]
edition = "2018"

[dependencies]
proc_macro_example = {path = "../proc_macro_example"}
proc_macro_example_level2 = {path = "../proc_macro_example_level2"}

